import type { Account, Transaction, RecurringItem, MonthlyBudget, Savings, Investment } from "../types/financial";

export const initialAccounts: Account[] = [
  {
    id: "acc-1",
    name: "토스 주거래 통장",
    type: "bank",
    balance: 4250000,
    institution: "토스뱅크",
    accountNumber: "1000-1234-5678",
    color: "#3b82f6",
  },
  {
    id: "acc-2",
    name: "KB 비상금 통장",
    type: "bank",
    balance: 10500000,
    institution: "KB국민은행",
    accountNumber: "4567-8901-2345",
    color: "#f59e0b",
  },
  {
    id: "acc-3",
    name: "신한 미스터라이프 카드",
    type: "credit_card",
    balance: -680000, // 이번 달 결제 예정액
    institution: "신한카드",
    creditLimit: 5000000,
    paymentDay: 14,
    color: "#06b6d4",
  },
  {
    id: "acc-4",
    name: "현대 네이버페이 카드",
    type: "credit_card",
    balance: -430000,
    institution: "현대카드",
    creditLimit: 3000000,
    paymentDay: 25,
    color: "#10b981",
  },
  {
    id: "acc-5",
    name: "한국투자증권 ISA/주식",
    type: "investment",
    balance: 24500000,
    institution: "한국투자증권",
    accountNumber: "ISA-998877",
    color: "#8b5cf6",
  },
  {
    id: "acc-6",
    name: "청년희망 적금",
    type: "savings",
    balance: 7200000,
    institution: "카카오뱅크",
    color: "#ec4899",
  },
  {
    id: "acc-7",
    name: "비상 현금",
    type: "cash",
    balance: 150000,
    color: "#64748b",
  }
];

export const initialRecurringItems: RecurringItem[] = [
  {
    id: "rec-1",
    title: "아파트 월세/관리비",
    type: "expense",
    amount: 650000,
    category: "주거/통신",
    accountId: "acc-1",
    dayOfMonth: 25,
    isActive: true,
    autoApply: true,
    memo: "매월 25일 자동이체",
  },
  {
    id: "rec-2",
    title: "넷플릭스 프리미엄",
    type: "expense",
    amount: 17000,
    category: "문화/여가",
    accountId: "acc-3",
    dayOfMonth: 5,
    isActive: true,
    autoApply: true,
    memo: "신한카드 정기결제",
  },
  {
    id: "rec-3",
    title: "쿠팡 와우 멤버십",
    type: "expense",
    amount: 7890,
    category: "쇼핑/의류",
    accountId: "acc-3",
    dayOfMonth: 12,
    isActive: true,
    autoApply: true,
    memo: "와우 회원 정기결제",
  },
  {
    id: "rec-4",
    title: "유튜브 프리미엄",
    type: "expense",
    amount: 14900,
    category: "문화/여가",
    accountId: "acc-4",
    dayOfMonth: 18,
    isActive: true,
    autoApply: true,
  },
  {
    id: "rec-5",
    title: "통신요금 (SKT)",
    type: "expense",
    amount: 59000,
    category: "주거/통신",
    accountId: "acc-3",
    dayOfMonth: 21,
    isActive: true,
    autoApply: true,
  },
  {
    id: "rec-6",
    title: "실손의료보험",
    type: "expense",
    amount: 42000,
    category: "금융/보험",
    accountId: "acc-1",
    dayOfMonth: 10,
    isActive: true,
    autoApply: true,
  },
  {
    id: "rec-7",
    title: "기본급 급여 입금",
    type: "income",
    amount: 4200000,
    category: "월급/급여",
    accountId: "acc-1",
    dayOfMonth: 25,
    isActive: true,
    autoApply: true,
    memo: "매월 25일 급여일",
  }
];

export const initialBudgets: Record<string, MonthlyBudget> = {
  "2026-08": {
    month: "2026-08",
    totalBudget: 2200000,
    categoryBudgets: {
      "식비": 600000,
      "카페/간식": 120000,
      "주거/통신": 750000,
      "교통/차량": 180000,
      "쇼핑/의류": 250000,
      "문화/여가": 150000,
      "의료/건강": 80000,
      "교육/자기계발": 70000,
    }
  }
};

export const initialSavings: Savings[] = [
  {
    id: "sav-1",
    title: "청년희망 적금",
    date: "2024-03-01",
    monthlyDeposit: 500000,
    annualRate: 5.5,
    targetMonths: 24,
    currentMonths: 18,
    goalAmount: 13000000,
    accountId: "acc-6",
    interestType: "simple",
    taxFree: true,
  },
  {
    id: "sav-2",
    title: "내집마련 청약저축",
    date: "2023-01-01",
    monthlyDeposit: 100000,
    annualRate: 2.8,
    targetMonths: 36,
    currentMonths: 20,
    goalAmount: 5000000,
    accountId: "acc-2",
    interestType: "compound",
    taxFree: false,
  }
];

export const initialInvestments: Investment[] = [
  {
    id: "inv-1",
    date: "2024-01-10",
    assetName: "삼성전자",
    ticker: "005930",
    market: "KR",
    buyPrice: 71000,
    quantity: 100,
    currentPrice: 78500,
    investedAmount: 7100000,
    evaluatedAmount: 7850000,
    profit: 750000,
    returnRate: 10.56,
    accountId: "acc-5",
    lastUpdated: "15:30:00",
  },
  {
    id: "inv-2",
    date: "2024-03-15",
    assetName: "엔비디아 (NVDA)",
    ticker: "NVDA",
    market: "US",
    buyPrice: 110000,
    quantity: 50,
    currentPrice: 135000,
    investedAmount: 5500000,
    evaluatedAmount: 6750000,
    profit: 1250000,
    returnRate: 22.73,
    accountId: "acc-5",
    lastUpdated: "15:30:00",
  },
  {
    id: "inv-3",
    date: "2024-05-20",
    assetName: "비트코인 (BTC)",
    ticker: "BTC",
    market: "CRYPTO",
    buyPrice: 82000000,
    quantity: 0.05,
    currentPrice: 89500000,
    investedAmount: 4100000,
    evaluatedAmount: 4475000,
    profit: 375000,
    returnRate: 9.15,
    accountId: "acc-5",
    lastUpdated: "15:30:00",
  }
];

export const initialTransactions: Transaction[] = [
  // 8월 수입
  {
    id: "tx-inc-1",
    date: "2026-08-25",
    type: "income",
    category: "월급/급여",
    amount: 4200000,
    accountId: "acc-1",
    memo: "8월 정기 급여",
    pension: 189000,
    health: 148890,
    longterm: 19072,
    employment: 37800,
    incomeTax: 252000,
    localTax: 25200,
    netAmount: 3528038,
  },
  {
    id: "tx-inc-2",
    date: "2026-08-10",
    type: "income",
    category: "부수입/사업",
    amount: 450000,
    accountId: "acc-1",
    memo: "외주 개발 프로젝트 대금 입금",
  },
  {
    id: "tx-inc-3",
    date: "2026-08-15",
    type: "income",
    category: "금융/배당금",
    amount: 85000,
    accountId: "acc-5",
    memo: "미국 ETF 분기 배당금 입금",
  },

  // 8월 지출
  {
    id: "tx-exp-1",
    date: "2026-08-25",
    type: "expense",
    category: "주거/통신",
    amount: 650000,
    accountId: "acc-1",
    memo: "8월 월세 및 오피스텔 관리비",
    isFixed: true,
    paymentMethod: "계좌이체",
  },
  {
    id: "tx-exp-2",
    date: "2026-08-05",
    type: "expense",
    category: "문화/여가",
    amount: 17000,
    accountId: "acc-3",
    memo: "넷플릭스 8월 정기구독",
    isFixed: true,
    paymentMethod: "신용카드",
  },
  {
    id: "tx-exp-3",
    date: "2026-08-12",
    type: "expense",
    category: "쇼핑/의류",
    amount: 7890,
    accountId: "acc-3",
    memo: "쿠팡 와우 멤버십",
    isFixed: true,
    paymentMethod: "신용카드",
  },
  {
    id: "tx-exp-4",
    date: "2026-08-01",
    type: "expense",
    category: "식비",
    amount: 45000,
    accountId: "acc-3",
    memo: "이마트 장보기 (식재료 및 생필품)",
    paymentMethod: "신용카드",
  },
  {
    id: "tx-exp-5",
    date: "2026-08-02",
    type: "expense",
    category: "카페/간식",
    amount: 6500,
    accountId: "acc-3",
    memo: "스타벅스 아이스 아메리카노 + 스콘",
    paymentMethod: "신용카드",
  },
  {
    id: "tx-exp-6",
    date: "2026-08-04",
    type: "expense",
    category: "교통/차량",
    amount: 55000,
    accountId: "acc-3",
    memo: "GS칼텍스 주유",
    paymentMethod: "신용카드",
  },
  {
    id: "tx-exp-7",
    date: "2026-08-07",
    type: "expense",
    category: "식비",
    amount: 32000,
    accountId: "acc-4",
    memo: "배달의민족 저녁 (초밥 세트)",
    paymentMethod: "신용카드",
  },
  {
    id: "tx-exp-8",
    date: "2026-08-09",
    type: "expense",
    category: "문화/여가",
    amount: 28000,
    accountId: "acc-4",
    memo: "CGV 영화 관람 (2인)",
    paymentMethod: "신용카드",
  },
  {
    id: "tx-exp-9",
    date: "2026-08-11",
    type: "expense",
    category: "쇼핑/의류",
    amount: 89000,
    accountId: "acc-4",
    memo: "무신사 여름 린넨 셔츠 & 슬랙스",
    paymentMethod: "신용카드",
  },
  {
    id: "tx-exp-10",
    date: "2026-08-14",
    type: "expense",
    category: "식비",
    amount: 68000,
    accountId: "acc-1",
    memo: "친구 모임 저녁 삼겹살 더치페이",
    paymentMethod: "체크카드",
  },
  {
    id: "tx-exp-11",
    date: "2026-08-16",
    type: "expense",
    category: "카페/간식",
    amount: 12000,
    accountId: "acc-1",
    memo: "주말 베이커리 카페 디저트",
    paymentMethod: "체크카드",
  },
  {
    id: "tx-exp-12",
    date: "2026-08-18",
    type: "expense",
    category: "의료/건강",
    amount: 35000,
    accountId: "acc-1",
    memo: "이비인후과 진료 및 약국 처방약",
    paymentMethod: "체크카드",
  },
  {
    id: "tx-exp-13",
    date: "2026-08-19",
    type: "expense",
    category: "교통/차량",
    amount: 62000,
    accountId: "acc-1",
    memo: "8월 지하철/버스 후불교통카드 정산",
    paymentMethod: "체크카드",
  },
  {
    id: "tx-exp-14",
    date: "2026-08-20",
    type: "expense",
    category: "교육/자기계발",
    amount: 49000,
    accountId: "acc-3",
    memo: "온라인 프로그래밍 강의 수강",
    paymentMethod: "신용카드",
  },

  // 7월 데이터
  {
    id: "tx-prev-1",
    date: "2026-07-25",
    type: "income",
    category: "월급/급여",
    amount: 4200000,
    accountId: "acc-1",
    memo: "7월 급여",
  },
  {
    id: "tx-prev-2",
    date: "2026-07-25",
    type: "expense",
    category: "주거/통신",
    amount: 650000,
    accountId: "acc-1",
    memo: "7월 월세",
    isFixed: true,
  },
  {
    id: "tx-prev-3",
    date: "2026-07-15",
    type: "expense",
    category: "식비",
    amount: 540000,
    accountId: "acc-3",
    memo: "7월 총 식비 합산",
  },
  {
    id: "tx-prev-4",
    date: "2026-07-20",
    type: "expense",
    category: "쇼핑/의류",
    amount: 190000,
    accountId: "acc-4",
    memo: "7월 쇼핑",
  }
];
